# Generated by Django 3.2.3 on 2021-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBasicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, error_messages={'null': "This field can't be null"}, max_length=50, null=True, unique=True)),
                ('description', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('is_live', models.BooleanField()),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
    ]
