# Generated by Django 3.2.3 on 2021-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBasicApp', '0007_auto_20210528_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='phone',
            field=models.TextField(),
        ),
    ]
